import { k } from "./game.js"

//this function loads all sounds
export default function loadSounds() {
  //all sounds are in the "sounds" folder
  k.loadSound("jump", "sounds/jump.wav")
  k.loadSound("slash", "sounds/sword.wav")
  k.loadSound("teleport", "sounds/teleport.wav")
  k.loadSound("death", "sounds/death.wav")
  k.loadSound("hit", "sounds/hit.wav")
  k.loadSound("heal", "sounds/heal.wav")
  k.loadSound("coin", "sounds/coin.wav")
  k.loadSound("pickup", "sounds/pickup.wav")
  k.loadSound("magic", "sounds/magic.wav")
  k.loadSound("clicking", "sounds/click.wav")
  k.loadSound("bossFight", "sounds/Kevin MacLeod - 8bit Dungeon Boss.mp3")
  k.loadSound("overworldMusic", "sounds/Pix - Space travel.mp3")
  k.loadSound("voiceline1", "sounds/voiceline1.wav")
  k.loadSound("voiceline2", "sounds/voiceline2.wav")
  k.loadSound("voiceline3", "sounds/voiceline3.wav")
  k.loadSound("voiceline4", "sounds/voiceline4.wav")
  k.loadSound("voiceline5", "sounds/voiceline5.wav")
  k.loadSound("voiceline6", "sounds/voiceline6.wav")
  k.loadSound("voiceline7", "sounds/voiceline7.wav")
  k.loadSound("voiceline8", "sounds/voiceline8.wav")
  k.loadSound("voiceline9", "sounds/voiceline9.wav")
  k.loadSound("voiceline10", "sounds/voiceline10.wav")
  k.loadSound("voiceline11", "sounds/voiceline11.wav")
  k.loadSound("voiceline12", "sounds/voiceline12.wav")
  k.loadSound("voiceline13", "sounds/voiceline13.wav")
  k.loadSound("voiceline14", "sounds/voiceline14.wav")
  k.loadSound("voiceline15", "sounds/voiceline15.wav")
  k.loadSound("voiceline16", "sounds/voiceline16.wav")
  k.loadSound("voiceline17", "sounds/voiceline17.wav")
  k.loadSound("voiceline18", "sounds/voiceline18.wav")
  k.loadSound("voiceline19", "sounds/voiceline19.wav")
  k.loadSound("voiceline20", "sounds/voiceline20.wav")
  k.loadSound("voiceline21", "sounds/voiceline21.wav")
  k.loadSound("voiceline22", "sounds/voiceline22.wav")
  k.loadSound("voiceline23", "sounds/voiceline23.wav")
  k.loadSound("voiceline24", "sounds/voiceline24.wav")
  k.loadSound("voiceline25", "sounds/voiceline25.wav")
  k.loadSound("voiceline26", "sounds/voiceline26.wav")
  k.loadSound("fire1", "sounds/fire1.wav")
  k.loadSound("fire2", "sounds/fire2.wav")
  k.loadSound("fire3", "sounds/fire3.wav")
  k.loadSound("fire4", "sounds/fire4.wav")
  k.loadSound("fire5", "sounds/fire5.wav")
}
